title: Hagiography of a geek
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6429971
  brandStrength: 0.3566308
  lightness: 0.2782416
  brandColors:
    - '#FFFFFF'
    - '#5288E0'
    - '#000004'
    - '#373E50'
    - '#D5BF9A'
  rhythmicContrast: 0.234767
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-76422014-1
  facebook: null
name: kevm
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6541219
layout_spectrum: 0.6308244
