name: kevm
favicon: null
layout_spectrum: 0.5559747745282948
typography_spectrum: 0.35799666307866573
title: Hagiography of a geek
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76422014-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6486661129165441
  lightness: 0.27824157010763884
  saturation: 0.6429970657918602
  rhythmicContrast: 0.1882688137702644
purpose: []
